run-name: Release ${{ inputs.version }}
name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Release version (e.g. 0.1.0)"
        required: true

permissions: {}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
        with:
          go-version: "1.25"

      - uses: acifani/setup-tinygo@b2ba42b249c7d3efdfe94166ec0f48b3191404f7 # v2.0.0
        with:
          tinygo-version: "0.40.1"

      - run: curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/1800853f2578f8c34492ec76154caef8e163fbca/install-from-binstall-release.sh | bash # v1.17.7
        env:
          BINSTALL_VERSION: 1.17.7

      - run: cargo binstall wasm-tools@1.245.1 -y

      - run: make build

      - uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: koyomi.wasm
          path: bin/koyomi.wasm

  build-wit:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - run: curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/1800853f2578f8c34492ec76154caef8e163fbca/install-from-binstall-release.sh | bash # v1.17.7
        env:
          BINSTALL_VERSION: 1.17.7

      - run: cargo binstall wkg@0.15.0 -y

      - run: wkg wit build -o koyomi_wit.wasm

      - uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: koyomi_wit.wasm
          path: koyomi_wit.wasm

  publish:
    needs: [build, build-wit]
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: koyomi_wit.wasm

      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: koyomi.wasm

      - run: curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/1800853f2578f8c34492ec76154caef8e163fbca/install-from-binstall-release.sh | bash # v1.17.7
        env:
          BINSTALL_VERSION: 1.17.7

      - run: cargo binstall wkg@0.15.0 -y

      - run: |
          wkg oci push \
            ghcr.io/a-skua/koyomi:${{ inputs.version }} \
            koyomi_wit.wasm
        env:
          WKG_OCI_USERNAME: ${{ github.actor }}
          WKG_OCI_PASSWORD: ${{ github.token }}

      - run: |
          wkg oci push \
            ghcr.io/a-skua/koyomi:${{ inputs.version }}-component \
            koyomi.wasm
        env:
          WKG_OCI_USERNAME: ${{ github.actor }}
          WKG_OCI_PASSWORD: ${{ github.token }}

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          merge-multiple: true

      - run: |
          HASH=$(echo "${{ github.sha }}" | cut -c1-4)
          gh release create "${VERSION}" \
            --title "${VERSION}" \
            --generate-notes \
            koyomi.wasm \
          || gh release create "${VERSION}+${HASH}" \
            --title "${VERSION}+${HASH}" \
            --generate-notes \
            koyomi.wasm
        env:
          VERSION: ${{ inputs.version }}
          GH_TOKEN: ${{ github.token }}
